# .github/workflows/sync_attachments_from_comments.yml
name: Sync attachments from author comments and body edits

on:
  issue_comment:
    types: [created, edited]
  issues:
    types: [edited]  # ← 追加：本文の編集イベントを拾う

permissions:
  contents: read
  issues: write

jobs:
  sync:
    # issue_comment か、issues.edited（body変更あり）の時だけ動く
    if: >
      (github.event_name == 'issue_comment') ||
      (github.event_name == 'issues' && github.event.action == 'edited' && github.event.changes.body != null)
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_REPOSITORY: ${{ github.repository }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Normalize attachments at top of issue body
        env:
          GITHUB_EVENT_PATH: ${{ github.event_path }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
        run: python sync_comment_attachments.py
