name: Sync attachments from author comments

on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write

jobs:
  sync:
    if: >
      github.event.issue != null &&
      github.event.comment != null &&
      github.event.issue.user.login == github.event.comment.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run sync script
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python .github/scripts/sync_comment_attachments.py
