name: Unified Attachments Pipeline

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]

# 同一Issue番号での並走を抑止
concurrency:
  group: unified-attachments-${{ github.event.issue.number }}
  cancel-in-progress: false

permissions:
  contents: write
  issues: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (requests / Pillow)
        run: |
          python -m pip install --upgrade pip
          pip install requests Pillow

      - name: Run unified pipeline (reorder + verify)
        id: unify
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_API_URL: https://api.github.com
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_EVENT_NAME: ${{ github.event_name }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          python unified_attachments_pipeline.py

      - name: Finalize issue state
        env:
          # verify.py が $GITHUB_OUTPUT に書いた出力を受け取って finalize に渡す
          VERIFICATION_RESULT: ${{ steps.unify.outputs.verification_result }}
          VERIFICATION_EXIT_CODE: ${{ steps.unify.outputs.verification_exit_code }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_API_URL: https://api.github.com
          GITHUB_REPOSITORY: ${{ github.repository }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          python finalize_issue.py
